stages:
  - lint
  - test

lint:
  stage: lint
  image: node:16.15-alpine
  before_script:
    - npm install
  script:
    - npm run lint

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
